apiVersion: v1
kind: Pod
metadata:
  name: debug-backup
  namespace: app
spec:
  containers:
  - name: debug-container
    image: mysql:8.0
    command: ["sleep", "3600"]
    # volumeMounts:
    # - name: mysql-backup
      # mountPath: /mnt/backups
  # volumes:
  # - name: mysql-backup
    # persistentVolumeClaim:
      # claimName: mysql-backup-pvc
