apiVersion: v1
kind: Pod
metadata:
  name: net-debug-container
  namespace: app
spec:
  containers:
  - name: net-debug-container
    image: nicolaka/netshoot
    command: ["sleep", "3600"]
    # volumeMounts:
    # - name: mysql-backup
      # mountPath: /mnt/backups
  # volumes:
  # - name: mysql-backup
    # persistentVolumeClaim:
      # claimName: mysql-backup-pvc
